# Generated by Django 4.0 on 2021-12-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_subject_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='classroom',
            field=models.IntegerField(null=True),
        ),
    ]
