# Generated by Django 4.0 on 2021-12-30 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_subject_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='next_session_begins',
        ),
    ]
