# Generated by Django 4.0 on 2021-12-25 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_takensubject_subjectallocation_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3)], max_length=1)),
                ('branch', models.CharField(blank=True, choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=1)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.session')),
                ('supervising_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6)], max_length=1)),
                ('weight', models.CharField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3)], max_length=1)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='repeatingstudent',
            name='student',
        ),
        migrations.RemoveField(
            model_name='subjectallocation',
            name='session',
        ),
        migrations.RemoveField(
            model_name='subjectallocation',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='subjectallocation',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='takensubject',
            name='student',
        ),
        migrations.RemoveField(
            model_name='takensubject',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subjectUnit',
        ),
        migrations.DeleteModel(
            name='CarryOverStudent',
        ),
        migrations.DeleteModel(
            name='RepeatingStudent',
        ),
        migrations.DeleteModel(
            name='SubjectAllocation',
        ),
        migrations.DeleteModel(
            name='TakenSubject',
        ),
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.class'),
        ),
    ]
