# Generated by Django 4.0 on 2021-12-25 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_class_grades_remove_repeatingstudent_student_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grades',
            new_name='Grade',
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
    ]
