# Generated by Django 4.0 on 2021-12-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_subject_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='year',
        ),
        migrations.AddField(
            model_name='student',
            name='students_class',
            field=models.CharField(blank=True, choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3)], max_length=1),
        ),
    ]
