# Generated by Django 4.0 on 2021-12-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_student_classes_remove_subject_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='students_class',
            field=models.CharField(blank=True, choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3)], max_length=1, null=True),
        ),
    ]
