# Generated by Django 4.0 on 2021-12-27 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_grade_subject_alter_teacher_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(choices=[('biology', 'biology'), ('civics', 'civics'), ('chemistry', 'chemistry'), ('English', 'English'), ('geography', 'geography'), ('German', 'German'), ('mathematics', 'mathematics'), ('physical education', 'physical education'), ('physics', 'physics'), ('Polish', 'Polish'), ('Spanish', 'Spanish')], max_length=200)),
                ('subjectCode', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('semester', models.CharField(choices=[('First', 'First'), ('Second', 'Second')], max_length=200)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.teacher')),
            ],
        ),
    ]
