# Generated by Django 4.0 on 2021-12-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_grade_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='branch',
            field=models.CharField(blank=True, choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.CharField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3)], max_length=1, null=True),
        ),
    ]
