# Generated by Django 4.0 on 2021-12-29 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_user_picture_user_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
    ]
